name: usb_debug_blocker
description: A Flutter plugin to detect Developer Options, USB connection, and MTP mode on Android devices.
version: 0.0.1
homepage: https://github.com/mohanveera/usb_debug_blocker  # Update if you use a real repo

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mohanveera.usb_debug_blocker
        pluginClass: UsbDebugBlockerPlugin
